### ISSUE TITLE
Refactor R code to read / use netcdf directly (bypassing Ruby code)

### ISSUE THREAD

**Issue by dlebauer** [ebimodeling/ghgvc#70]
The ruby code used to extract data from netcdf files is hacky and needs to be revised. Likely, R is better equipped to handle this. There are many R functions in github.com/pecanproject/pecan R packages for extracting and writing netcdf using the package `ncdf`.

The overall functionality we need to keep

1. user selects location (ruby interface)
2. location is passed to R
3. R queries and returns biome names and values from netcdf file / 

## TODO

* [ ] review [workflows_controller.rb](https://github.com/ebimodeling/ghgvc/blob/master/app/controllers/workflows_controller.rb)
  * [ ] document current functionality of workflows_controller.rb
  * [ ] propose refactoring approach (include function names, inputs, outputs, how information will be communicated between R and Ruby, and where in the ruby code this will occur)
* [ ] move netcdf queries from ruby to use R  
  * [ ] write tests for workflows_controller
  * [x] remove netcdf data query from workflows_controller.rb 
  * [x] add queries to R package as functions that can be called from workflows_controller.rb and return json objects that workflows_controller can read
  * [ ] implement functions, with tests and examples (a vignette)

**Comment by potterzot** [comment]
@dlebauer I'd be interested in taking this on if I seem like a good fit. Here are my initial thoughts:

If you want to transfer the ruby code to R, much of the specific netcdf data fetching could be rewritten into a generic function fairly easily, something like:

    #psuedo R code to access netcdf data
    #' @importFrom ncdf open.ncdf get.var.ncdf
    #' @export
    #'
    #' @param ncdf_url (character) location of netcdf data.
    #' @param lat the latitude.
    #' @param lon the longitude.
    #' @param var the variable to fetch.
    #' @param start an array of dimension indices to start at.
    #' @param count an array of counts along each dimension to fetch.
    #' @return a data.frame of netcdf data
    get_netcdf <- function(ncdf_url, lat, lon, var, start, count) {
      #open an ncdf connection
      con = open.ncdf(ncdf_url)
      
      # Just get a single lat/lon
      start_idx = c(lat, lon, start)
      count_idx = c(1, 1, count)

      get.var.ncdf(con, var, start_idx, count_idx)
    }

This function would access data for a specific variable and lat/lon pair and would have enough flexibility to do so for any netcdf file. The tradeoff would be more processing outside of the function to set the start/count dimensions, but perhaps this function could wrap more specialized functions to remove that need. There is also some ability to automate that to the extent that a variable dimension only has a single variable, etc...

I wrote the gefs module that just got accepted to [rnoaa](https://github.com/ropensci/rnoaa) and deals with some of this same functionality, so it might be worth taking a look at that.

I hope that helps. Let me know if you're interested. Thanks.

**Comment by Autodidact24** [comment]
Hi @dlebauer,
I would like to work on this. The Ruby implementation is a bit hacky and hard to read. Using R/Python makes it easier to read and write netCFD files. There are R packages to read, index, slice netCFD data.
Only a few features ("lat", "lon") need to read and manipulated.

**Comment by Yuanchao-Xu** [comment]
Hi @dlebauer ,

I just happend to see this, and it seems one of functions from my package "hyfo" can solve this problem. (getFrcEnsem from hyfo).

Description of the function can be found [here](https://cran.r-project.org/web/packages/hyfo/hyfo.pdf)

**Comment by dlebauer** [comment]
@Yuanchao-Xu Thanks! I'll leave it to @potterzot to decide if he will use this here, but it definitely seems a good fit for github.com/pecanproject/pecan (@pecanproject/pecan-developers); perhaps also useful for  github.com/terraref/computing-pipeline

**Comment by Yuanchao-Xu** [comment]
@dlebauer My pleasure, if needed, I can make some improvements for special cases.

**Comment by potterzot** [comment]
@Yuanchao-Xu Cool, thanks! I'll have to have a deeper look but could be useful. Your [ncdf](https://github.com/Yuanchao-Xu/hyfo/blob/master/R/ncdf.R) functionality in particular could be useful. Are you converting to ncdf4 any time soon?

**Comment by Yuanchao-Xu** [comment]
@potterzot yes I can transfer to ncdf4, but according to the discussion with the author of the ncdf4, it has to be installed from source on CRAN, i.e., in order to use it, you have to install the C library as well, which is not so easy for the users to install, so I turn to ncdf instead. However, if for special case, and no need to consider the convenience for normal users, I can convert to ncdf4, it's only function names.

**Comment by potterzot** [comment]
@Yuanchao-Xu Sure, just a thought really. Recently converted the [rnoaa](https://github.com/ropensci/rnoaa) package (not that I am a maintainer, I just wrote a small part of it) to ncdf4 b/c binaries are now available on windows.

We've already got netcdf functionality both here and in rnoaa/R/gefs.R and it probably doesn't make sense to rewrite at the moment, but I would definitely love a standardized set of tools for working with netcdf at a slightly higher level than ncdf and ncdf4, which it seems like you've written, so I'll keep it in mind for the future.

Also, FWIW, the [ghgvc install.dependencies.R](https://github.com/ebimodeling/ghgvc/blob/master/install.dependencies.R) script includes ncdf4, so unless @dlebauer thinks otherwise we'll probably stick with that to reduce dependencies.

**Comment by dlebauer** [comment]
I haven't worked much with ncdf but according to the [ncdf package description it is being deprecated](https://cran.r-project.org/web/packages/ncdf/index.html).

**Comment by Yuanchao-Xu** [comment]
@dlebauer @potterzot  OK I'll try to do it, is there a deadline or sth?

**Comment by Yuanchao-Xu** [comment]
@dlebauer @potterzot  OK, done. I've transferred all the related functions from ncdf to ncdf4. It passes travis(Linux) and windows check. While for some special case with ncdf4 files, more changes will need to be made, e.g. writing version4 ncdf file. But that can be modified with future cases. Right now I don't have any version4 file at hand....I cannot test...

**Comment by dlebauer** [comment]
I think this is netCDF 4 https://github.com/PecanProject/pecan/blob/master/models/biocro/tests/testthat/data/urbana_subdaily_test.nc

**Comment by dlebauer** [comment]
@Yuanchao-Xu here are a few more netcdf-4 files: http://file-server.igb.illinois.edu/~dlebauer/met/narr/threehourly/

**Comment by Yuanchao-Xu** [comment]
OK，I'll have a look at it asap~

**Comment by Yuanchao-Xu** [comment]
@dlebauer  @potterzot Right now it should work with version 4 file for both loading and writing. But there is one problem about your version 4 file. For some variables like "crs" and "lat_bnds" , there are only two dimensions inside the file, I don't quite understand what these variables are for.

**Comment by dlebauer** [comment]
@potterzot can this issue be closed?

**Comment by Yuanchao-Xu** [comment]
@potterzot just wondering, at last how it is solved in your project?

**Comment by potterzot** [comment]
Yep, this is all set, excepting a response to @Yuanchao-Xu. Closing
